name: Extract scripts and mod file and upload

on:
  workflow_call:
    inputs:
      file_id:
        required: true
        type: string
      mod_version:
        required: false
        type: string
        default: ''
      mod_description:
        required: false
        type: string
        default: ''
      checkout_ref:
        required: true
        type: string
      upload:
        type: boolean
        default: true
    secrets:
      NEXUSMODS_APIKEY:
        required: true

jobs:
  pack-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Make Directory
        run: mkdir src
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout_ref }}
          path: './src'
      - name: Repack zipball to be inside mod folder
        id: mod-repack
        run: |
          FILENAME=$(ls -1 ./src/*.mod | xargs -0 basename)
          MODNAME=${FILENAME%.mod}
          mkdir out out/"${MODNAME}"
          set +e
          mv ./src/scripts ./src/audio ./src/content ./src/dialogues ./src/"${MODNAME}.mod" ./out/"${MODNAME}"
          echo "modname=\"${MODNAME}\"" >> "$GITHUB_OUTPUT"
      - name: Zip File
        run: zip -r ${{ fromJson(steps.mod-repack.outputs.modname) }}.zip ./out/${{ fromJson(steps.mod-repack.outputs.modname) }}
      - name: Upload File
        id: nexus-upload
        uses: Nexus-Mods/upload-action@v1.0.0-beta.8
        if: ${{ inputs.upload }}
        with:
          api_key: ${{ secrets.NEXUSMODS_SESSION_COOKIE }}
          file_id: ${{ inputs.file_id }}
          filename: ${{ fromJson(steps.mod-repack.outputs.modname) }}.zip
          version: ${{ inputs.mod_version }}
          description: ${{ inputs.mod_description }}
    outputs:
      mod_name: ${{ fromJson(steps.mod-repack.outputs.modname) }}
      version: ${{ steps.nexus-upload.outputs.version_id }}
    
